VIV-69 VIV-60 Connexion et logo
VivaBABP/VivaRecruit_Mobile pull request #10
Opened 2023-05-08 19:37 UTC by JulienBois

2023-05-09 11:04 UTC, huhulacolle requested changes
- la partie authent pour une V1, quand tu gèreras la connexion via token il faudra légèrement le changer
- Les icônes me paraissent un peu trop grosses, je te conseille de te baser sur les fichiers images déjà présents dans le dossier assets, (si tu veux pas faire la même erreur que moi au début avec l’icône de ActuWorld beaucoup trop grosse)

2023-05-09 11:10 UTC, huhulacolle requested changes
![image](https://github.com/VivaBABP/VivaRecruit_Mobile/assets/66556677/4b2afc26-6443-48fa-bd56-618070f5cfe0)
Après avoir testé en mettant un compte qui n'existait pas, j'ai voulu supprimer le faux adresse mail et cette erreur est apparu

2023-05-10 09:39 UTC, JulienBois commented
> ![image](https://github.com/VivaBABP/VivaRecruit_Mobile/assets/66556677/4b2afc26-6443-48fa-bd56-618070f5cfe0)
> Après avoir testé en mettant un compte qui n'existait pas, j'ai voulu supprimer le faux adresse mail et cette erreur est apparu

Des changements ont été effectués pour régler ce problème

2023-05-11 06:59 UTC, JulienBois commented
> * la partie authent est bien pour une V1 mais quand tu gèreras la connexion via token il faudra légèrement le changer
> * Les icônes me paraissent un peu trop grosses, je te conseille de te baser sur les fichiers images déjà présents dans le dossier assets, (si tu veux pas faire la même erreur que moi au début avec l’icône de ActuWorld beaucoup trop grosse)

Les icônes ont été revues pour être plus petites et l'authentification a été revue aussi

2023-05-11 07:04 UTC, huhulacolle approved these changes

2023-05-11 07:10 UTC, huhulacolle requested changes
dans Home.tsx
appelle la fonction disconnect du context plutôt que de faire un navigation.popToTop() (qui ne marche plus du coup)

2023-05-11 07:31 UTC, huhulacolle submitted a review, later dismissed

2023-05-11 07:36 UTC, huhulacolle approved these changes

2023-05-11 07:40 UTC, sacha0914 approved these changes

2023-05-11 07:40 UTC, merged