VIV-72 création de fiche de poste -> api
VivaBABP/VivaRecruit_Mobile pull request #11
Opened 2023-05-11 18:29 UTC by huhulacolle

2023-05-11 20:50 UTC, JulienBois requested changes
Il faut reprendre le message de création de job mais sinon du bon boulot

2023-05-12 09:27 UTC, JulienBois submitted a review, later dismissed

2023-05-12 13:14 UTC, JulienBois approved these changes
Merci pour avoir pris en compte le message)

2023-05-12 13:34 UTC, sacha0914 approved these changes

2023-05-12 13:34 UTC, merged