VIV-65  Feature/interest
VivaBABP/VivaRecruit_Mobile pull request #20
Opened 2023-05-24 15:00 UTC by sacha0914

2023-05-24 17:39 UTC, JulienBois requested changes
Il serait bien d'afficher les intérêts existants du compte sur la page et de changer le logo, tu peux en profiter pour faire les changements graphiques via les maquettes en même temps

2023-05-25 11:40 UTC, huhulacolle submitted a review, later dismissed

2023-05-25 11:53 UTC, GianniB77 submitted a review, later dismissed

2023-05-25 11:55 UTC, GianniB77 approved these changes

2023-05-25 11:55 UTC, huhulacolle approved these changes

2023-05-25 11:57 UTC, JulienBois approved these changes

2023-05-25 11:57 UTC, merged